# Generated by Django 4.1.6 on 2023-04-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="primary",
            field=models.ImageField(blank=True, null=True, upload_to="Product Images"),
        ),
        migrations.AddField(
            model_name="product",
            name="secondary",
            field=models.ImageField(blank=True, null=True, upload_to="Product Images"),
        ),
    ]
