# Generated by Django 4.1.6 on 2023-05-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_order_cart_order_order_total_orderitems"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ordernote",
            field=models.TextField(blank=True, null=True),
        ),
    ]
