# Generated by Django 4.1.6 on 2023-05-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_order_ordernote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipping",
            old_name="Address",
            new_name="sAddress",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="city",
            new_name="scity",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="company_name",
            new_name="scompany_name",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="country",
            new_name="scountry",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="email",
            new_name="semail",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="first_name",
            new_name="sfirst_name",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="last_name",
            new_name="slast_name",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="phone",
            new_name="sphone",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="state",
            new_name="sstate",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="zipcode",
            new_name="szipcode",
        ),
    ]
