# Generated by Django 4.1.6 on 2023-05-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_address_shipping_saddress_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="shipping",
            old_name="sAddress",
            new_name="shipping_Address",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="scity",
            new_name="shipping_city",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="scompany_name",
            new_name="shipping_company_name",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="scountry",
            new_name="shipping_country",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="semail",
            new_name="shipping_email",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="sfirst_name",
            new_name="shipping_first_name",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="slast_name",
            new_name="shipping_last_name",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="sphone",
            new_name="shipping_phone",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="sstate",
            new_name="shipping_state",
        ),
        migrations.RenameField(
            model_name="shipping",
            old_name="szipcode",
            new_name="shipping_zipcode",
        ),
    ]
