# Generated by Django 4.1.6 on 2023-05-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customer_shipping_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Order",
        ),
        migrations.DeleteModel(
            name="Shipping",
        ),
    ]
